FROM nginx:alpine

COPY infra/docker/nginx/default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /var/www/html/public
COPY public/index.php public/robots.txt public/favicon.ico public/.htaccess /var/www/html/public/

RUN chmod -R 755 /var/www/html/public

EXPOSE 80
